### ISSUE TITLE
Sap Cloud Platform

### ISSUE THREAD

**Issue by kevin-bebel** [SAP/goauth-handlers#4]
Hi

Is there any way to use this tool to authenticate against sap cloud platform?

Thanks

**Comment by momchil-sap** [comment]
@kevin-bebel , could you provide a bit more information what your use case is. Which OAuth flow are you interested in? Against which OAuth server do you want to use this?

**Comment by kevin-bebel** [comment]
Hi @momchil-sap 

We currently have a client using SAP Cloud Platform, and they want us to authenticate against SCP. We are using SCP's Oauth2 service to authenticate users using a hybrid mobile app we have create. The problem is that it does not return to us jwt token but instead a tradition session token if I am not mistaken. We are need a way to be able to extract user information from the token.

**Comment by momchil-sap** [comment]
This project has currently support only for the `authorization code grant` flow, where a service wants to act on behalf of some user. We have tested and used it against a Cloud Foundry UAA server (OAuth service).

From what I can understand in your scenario, you seem to be using a different type of OAuth flow.
